
server:
  port: 

spring:
  # PostgreSQL DB 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 
    username: 
    password: 

# Mybatis 설정
mybatis:
  # default Package location - resultType의 Alias를 지정합니다.
  type-aliases-package: 
  # mapper location - 바라 볼 xml 파일을 지정합니다.
  mapper-locations: 

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: 
  access-token-validity-in-seconds: 10000
  refresh-token-validity-in-seconds: 10000
